site_name: FastAPI Stock & Crypto Data API
site_description: Comprehensive API documentation for stock market data and cryptocurrency prices
site_author: FastAPI Team

# Repository
repo_name: FastAPI-Stock-data-
repo_url: https://github.com/OMCHOKSI108/FastAPI-Stock-data-

# Theme
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - codehilite
  - toc:
      permalink: true

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
      - Stock Data: api/stock.md
      - Crypto Data: api/crypto.md
      - Market Data: api/market.md
      - Analytics: api/analytics.md
  - Symbol Reference:
      - NSE Stocks: symbols/nse-stocks.md
      - Cryptocurrencies: symbols/cryptocurrencies.md
      - Indices: symbols/indices.md
  - Examples: examples.md
  - Deployment: deployment.md

# Plugins
plugins:
  - search
